### ISSUE TITLE
"Adding KCP or UDT protocol to Kaillera to optimize online network."

### ISSUE THREAD

**Issue by hildoszlengq** [hopskipnfall/EmuLinker-K#105]

**Comment by hopskipnfall** [comment]
Hi hildoszlengq, thanks for the suggestion.

I'm not familiar with KCP or UDT, but unfortunately we aren't in a position to materially change our protocol over the wire as it would require breaking compatibility with existing clients so I doubt this is feasible. Is there anything specific from KCP or UDT that you propose we adopt?

**Comment by hildoszlengq** [comment]
Yes,Related Protocol Projects (Reference).

https://github.com/JohannesBuchner/udt-java

https://github.com/szhnet/kcp-netty

https://github.com/ubijak3/JavaUTP

**Comment by hildoszlengq** [comment]
I particularly recommend referring to this project as it will provide long-term support and updates.

https://github.com/skywind3000/kcp/blob/master/README.en.md

**Comment by hopskipnfall** [comment]
Unless I'm mistaken, this would involve breaking compatibility with existing clients which is outside of the [priorities](https://github.com/hopskipnfall/EmuLinker-K/blob/master/CONTRIBUTING.md#priorities) for this project.

From a glance I'm also not convinced that it would improve latency for users so it doesn't seem worth it.
