### ISSUE TITLE
Are there any plans to make kaillera for phone?

### ISSUE THREAD

**Issue by mxsymeg** [hopskipnfall/EmuLinker-K#120]
It is hoped that this item can be included in the plan.

**Comment by mxsymeg** [comment]
Eventually it will be possible to realize online battles between pc and Android.

**Comment by hopskipnfall** [comment]
Hi @mxsymeg, this is a better question for the [discord](https://discord.gg/MqZEph388c). This repository is just the server backend, not client-related. There might be a kaillera client that works on Android but I'm not aware of it.
