### ISSUE TITLE
Some games go out of sync in the middle of the game

### ISSUE THREAD

**Issue by mxsymeg** [hopskipnfall/EmuLinker-K#121]
Game screen out of sync problem occurs in MAME emulator and RetroArch emulator MAME system

**Comment by mxsymeg** [comment]
PGM2 system games online all go out of sync and everyone has low latency, I'd like to know what's wrong and improve it, thanks.

**Comment by hopskipnfall** [comment]
I think it's unlikely this going out of sync issue is caused by the server. It's probably an issue with the emulator or the kaillera client dll you're using.
