### ISSUE TITLE
Timed restart of the server programme

### ISSUE THREAD

**Issue by mxsymeg** [hopskipnfall/EmuLinker-K#127]
After running server.bat for a while, the kaillera list does not show the server and the server cannot be accessed by ip address.

**Comment by mxsymeg** [comment]
I hope to add the function of restarting the server programme at regular intervals in the subsequent versions.

**Comment by hopskipnfall** [comment]
@mxsymeg The next time this happens, can you look at the emulinker.log file and see if it shows any error messages towards the end?
