### ISSUE TITLE
Can the udp protocol be improved in subsequent releases

### ISSUE THREAD

**Issue by mxsymeg** [hopskipnfall/EmuLinker-K#132]
Some udp protocol solutions

https://github.com/HeatXD/EthernetHotel.js

https://github.com/HeatXD/GekkoNet

https://github.com/HeatXD/HostRegister

**Comment by hopskipnfall** [comment]
Can you explain what your specific criticism with the protocol is and how those repositories might be used to address it? Keep in mind we will not make any change that would break compatibility with existing clients.
